<div class="page-header">
    <div class="container">
        <h1>Latar Belakang</h1>
        <p>Di era kemajuan teknologi informasi yang sangat perkembangang pesat seperti sekarang ini banyak sekali keuntungan yang bisa diperoleh dari perkembangan teknologi informasi ini, teknologi informasi mempunyai peran yang penting mencakup segelah aspek bidang,. Sebagai contoh dibidang teknik sipil pemanfaatan Sistem Informasi Geografis saat ini dapat untuk mengetahui posisi wilayah secara visualisasi. Sistem informasi geografis dirancang untuk proses mengumpulkan, menyimpan dan menganalisis obyek, di mana lokasi geografis menjadi karakteristik yang penting dalam sistem ini dapat mengintegrasikan data spasial (Peta vektor dan citra digital), atribut (tabel basis data), dan lain sebagainya.</p>
        <p>Sistem Informasi Geografis (SIG) ini menjadi solusi untuk melakukan pemetaan ruas jaringan jalan, membatu dalam pengelolaan data yang baik terhadap sistem jaringan jalan dan juga masyarakat umum memperoleh informasi tentang kondisi jalan.</p>
        <p>Jalan merupakan suatu prasarana perhubungan darat dan jalur transportasi yang sangat vital. Salah satu fungsi jalan adalah sebagai faktor pendorong dalam proses pengembangan serta pemerataan pembangunan suatu wilayah, selain itu jalan juga sangat berperan penting dalam proses perhubungan. Tersedianya
            infrastruktur jaringan jalan yang memadai merupakan salah satu modal besar untuk meningkatkan kegiatan masyarakat di suatu daerah, baik untuk kegiatan yang bersifat sosial maupun perekonomian. Selain sebagai transportasi, jalan juga berfungsi sebagai media sosialisasi dan aksesibilitas bagi masyarakat. Jika kondisi jalan baik, maka aktifitas perekonomian dan transportasi juga akan menjadi lancar. (Lauryn & Ibrohim, 2019)
        </p>
        <p>Namun jalan yang digunakan terkadang tidak sesui dengan apa yang diharapkan, ini di karnakan jalan yang dilalui oleh pengguna jalan sering megalami kerusakan </p>
        <p>Menurut Dinas Pekerjaan Umum dan Penataan Ruang Kabupaten Buton Utara, di daerah Kabupaten Buton Utara ini masi banyak ruas jalan yang rusak ringan maupun rusak berat, kerusakan jalan tersebut merupakan permasalahan yang sangat kompleks kerugian dan dampak yang diderita sungguh besar bagi masyarakat pengguna jalan, seperti terjadinya kecelakaan lalulintasa, waktu tempuh yang lama dan lain-lain. Sedangkan pemetaan dan penelitian khususnya terhadap kondisi jalan selama ini masi kurang di perhatikan.</p>
        <p>Dengan menyadari perlu sebua informasi mengenai kerusakan jalan yang bisa menempilkan kondisi ruas jalan Provinsi yang ada di Kabupaten Buton Utara. Sistem informasi yang akan di tempilkan berupa peta digital yang berbasis Sistem Informasi Geografis (SIG) ini lebih evfektif untuk memeberikan visualisasi data kerusakan ruas jalan, kondisi jalan dan laporan kerusakan ruas jalan khususnya di ruasjalan provinsi di Kabupaten Buton Utara </p>
    </div>
</div>